FROM mcr.microsoft.com/windows/nanoserver:ltsc2022-amd64
LABEL org.opencontainers.image.description='LAStools for Windows'

COPY VC_redist.x64 C:\\Windows\\System32
	
COPY PROJ C:\\Data\\PROJ
ENV PROJ_DATA=C:\\Data\\PROJ

RUN curl -kqL https://downloads.rapidlasso.de/LAStools.zip -o %TMP%\LAStools.zip & \
    mkdir C:\LAStools & \
    tar -xvf %TMP%\LAStools.zip -C C:\LAStools bin/*.exe bin/*.dll bin/*.csv & \
    del %TMP%\LAStools.zip & \
    setx PATH "C:\LAStools\bin;%PATH%"
