// -----------------------------------------------------------------------
// <copyright file="IUnion.cs" company="Altemiq">
// Copyright (c) Altemiq. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

#pragma warning disable IDE0130, CheckNamespace
namespace System.Runtime.CompilerServices;
#pragma warning restore IDE0130, CheckNamespace

/// <summary>
/// Provides a common interface for accessing the contents of a union type at runtime.
/// </summary>
/// <remarks>
/// <para>
/// The C# compiler automatically implements this interface on types generated by union declarations.
/// User-defined types annotated with <see cref="UnionAttribute" /> may also implement this interface
/// to provide runtime access to the union's value. Implementing this interface is not required
/// for union behaviors provided by the compiler.
/// </para>
/// </remarks>
/// <seealso cref="UnionAttribute" />
[Microsoft.CodeAnalysis.Embedded]
internal interface IUnion
{
    /// <summary>
    /// Gets the value contained in the union, or <see langword="null" /> if the union has no value.
    /// </summary>
    /// <value>
    /// The current value of the union as one of its case types, or <see langword="null" />.
    /// </value>
    object? Value { get; }
}