name: container
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:3
        ports:
          - 5000:5000
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      
      - uses: docker/build-push-action@v6
        with:
          context: {{defaultContext}}:container
          push: false
          tags: localhost:5000/${{ github.repository_owner }}/lastools:latest-ubuntu
          file: ContainerFile.ubuntu